/*
 * Copyright © 2020-2023 THALES. All rights reserved.
 */

// IMPORTANT: This source code is intended to serve training information purposes only.
//            Please make sure to review our IdCloud documentation, including security guidelines.

@interface Provisioning_Logic : NSObject

/**
 Asynchronous method to provision token based on user id and registration code from tutorial page.

 @param userId User id generated by tutorial page. It will be also used as token name.
 @param regCode Registration code generated by tutorial page.
 @param completionHandler Handler triggered once operation is finished.
 */
+ (void)provisionWithUserId:(NSString * _Nonnull)userId
           registrationCode:(id<EMSecureString> _Nonnull)regCode
          completionHandler:(void (^_Nonnull)(id<EMOathToken> _Nullable token, NSError * _Nullable error))completionHandler;


/**
 Method will return first provisioned token or nil if there is not any.

 @return Token or nil.
 */
+ (id<EMOathToken>_Nullable)token;


/**
 It will delete first provisioned token.

 @param error Error description
 @return YES if operation was succesfull.
 */
+ (BOOL)removeToken:(NSError *_Nullable*_Nullable)error;

@end
