/* -----------------------------------------------------------------------------
 *
 *     Copyright (c) 2015  -  GEMALTO DEVELOPMENT - R&D
 *
 * -----------------------------------------------------------------------------
 * GEMALTO MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY OF
 * THE SOFTWARE, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED
 * TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE, OR NON-INFRINGEMENT. GEMALTO SHALL NOT BE
 * LIABLE FOR ANY DAMAGES SUFFERED BY LICENSEE AS A RESULT OF USING,
 * MODIFYING OR DISTRIBUTING THIS SOFTWARE OR ITS DERIVATIVES.
 *
 * THIS SOFTWARE IS NOT DESIGNED OR INTENDED FOR USE OR RESALE AS ON-LINE
 * CONTROL EQUIPMENT IN HAZARDOUS ENVIRONMENTS REQUIRING FAIL-SAFE
 * PERFORMANCE, SUCH AS IN THE OPERATION OF NUCLEAR FACILITIES, AIRCRAFT
 * NAVIGATION OR COMMUNICATION SYSTEMS, AIR TRAFFIC CONTROL, DIRECT LIFE
 * SUPPORT MACHINES, OR WEAPONS SYSTEMS, IN WHICH THE FAILURE OF THE
 * SOFTWARE COULD LEAD DIRECTLY TO DEATH, PERSONAL INJURY, OR SEVERE
 * PHYSICAL OR ENVIRONMENTAL DAMAGE ("HIGH RISK ACTIVITIES"). GEMALTO
 * SPECIFICALLY DISCLAIMS ANY EXPRESS OR IMPLIED WARRANTY OF FITNESS FOR
 * HIGH RISK ACTIVITIES.
 *
 * -----------------------------------------------------------------------------
 */

#import <Foundation/Foundation.h>

/**
 * Domains of Ezio mobile error
 *
 * - Since: 3.0
 */

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wstrict-prototypes"

///
extern NSString * EZIO_MOBILE_ERROR_DOMAIN_TOKEN;
///
extern NSString * EZIO_MOBILE_ERROR_DOMAIN_FINGERPRINT;
///
extern NSString * EZIO_MOBILE_ERROR_DOMAIN_JAILBREAK_DETECTION;
///
extern NSString * EZIO_MOBILE_ERROR_DOMAIN_OOB;
///
extern NSString * EZIO_MOBILE_ERROR_DOMAIN_PASSWORD;
///
extern NSString * EZIO_MOBILE_ERROR_DOMAIN_SECURE_STORAGE;
///
extern NSString * EZIO_MOBILE_ERROR_DOMAIN_UNSPECIFIED;
///
extern NSString * EZIO_MOBILE_ERROR_DOMAIN_AUTH_MODE_BIOFP;
///
extern NSString * EZIO_MOBILE_ERROR_DOMAIN_AUTH_MODE_SYSTEM_FACEID;
///
extern NSString * EZIO_MOBILE_ERROR_DOMAIN_AUTH_MODE_FACE;
///
extern NSString * EZIO_MOBILE_ERROR_DOMAIN_MULTI_AUTH_MODE;
///
extern NSString * EZIO_MOBILE_ERROR_DOMAIN_EMS_LICENSE;
///
extern NSString * EZIO_MOBILE_ERROR_DOMAIN_MSP;
///
extern NSString * EZIO_MOBILE_ERROR_DOMAIN_GLOBALDB;
///
extern NSString * EZIO_MOBILE_ERROR_DOMAIN_SPRNG;


#pragma clang diagnostic pop
